version: '2'
services:

  web:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - "3000-3001:3000-3001"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/geekplanet"

  mongo:
    image: mongo
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
