version: '3'
services:
  web:
    image: r3ddox/node-pdftk:11.8.0
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000-3001:3000-3001"
      - "9229:9229"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/geekplanet"

  mongo:
    image: mongo:3.6.6
    command: mongod --smallfiles
    ports:
      - "27017:27017"
