// flow-typed signature: 1afce524bc2365eec24fb26b3a85575b
// flow-typed version: <<STUB>>/bestzip_v1.1.3/flow_v0.37.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bestzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bestzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bestzip/bin/cli' {
  declare module.exports: any;
}

declare module 'bestzip/lib/bestzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bestzip/bin/cli.js' {
  declare module.exports: $Exports<'bestzip/bin/cli'>;
}
declare module 'bestzip/lib/bestzip.js' {
  declare module.exports: $Exports<'bestzip/lib/bestzip'>;
}
