// flow-typed signature: 3aaa3a4e3923aa5e0f9e62bdece2e4d2
// flow-typed version: <<STUB>>/body-parser_v1.17.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'body-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'body-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'body-parser/lib/read' {
  declare module.exports: any;
}

declare module 'body-parser/lib/types/json' {
  declare module.exports: any;
}

declare module 'body-parser/lib/types/raw' {
  declare module.exports: any;
}

declare module 'body-parser/lib/types/text' {
  declare module.exports: any;
}

declare module 'body-parser/lib/types/urlencoded' {
  declare module.exports: any;
}

// Filename aliases
declare module 'body-parser/index' {
  declare module.exports: $Exports<'body-parser'>;
}
declare module 'body-parser/index.js' {
  declare module.exports: $Exports<'body-parser'>;
}
declare module 'body-parser/lib/read.js' {
  declare module.exports: $Exports<'body-parser/lib/read'>;
}
declare module 'body-parser/lib/types/json.js' {
  declare module.exports: $Exports<'body-parser/lib/types/json'>;
}
declare module 'body-parser/lib/types/raw.js' {
  declare module.exports: $Exports<'body-parser/lib/types/raw'>;
}
declare module 'body-parser/lib/types/text.js' {
  declare module.exports: $Exports<'body-parser/lib/types/text'>;
}
declare module 'body-parser/lib/types/urlencoded.js' {
  declare module.exports: $Exports<'body-parser/lib/types/urlencoded'>;
}
