// flow-typed signature: bb1e5312ce3c699595747e9fc7fee846
// flow-typed version: <<STUB>>/coupon-code_v0.4.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coupon-code'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coupon-code' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coupon-code/coupon-code' {
  declare module.exports: any;
}

declare module 'coupon-code/test/badWords' {
  declare module.exports: any;
}

declare module 'coupon-code/test/generate' {
  declare module.exports: any;
}

declare module 'coupon-code/test/load' {
  declare module.exports: any;
}

declare module 'coupon-code/test/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coupon-code/coupon-code.js' {
  declare module.exports: $Exports<'coupon-code/coupon-code'>;
}
declare module 'coupon-code/test/badWords.js' {
  declare module.exports: $Exports<'coupon-code/test/badWords'>;
}
declare module 'coupon-code/test/generate.js' {
  declare module.exports: $Exports<'coupon-code/test/generate'>;
}
declare module 'coupon-code/test/load.js' {
  declare module.exports: $Exports<'coupon-code/test/load'>;
}
declare module 'coupon-code/test/validate.js' {
  declare module.exports: $Exports<'coupon-code/test/validate'>;
}
