// flow-typed signature: eb5c3990c3021f4b4cc4070bdeb9d877
// flow-typed version: <<STUB>>/express-mongo-sanitize_v1.3.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-mongo-sanitize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-mongo-sanitize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-mongo-sanitize/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-mongo-sanitize/index' {
  declare module.exports: $Exports<'express-mongo-sanitize'>;
}
declare module 'express-mongo-sanitize/index.js' {
  declare module.exports: $Exports<'express-mongo-sanitize'>;
}
declare module 'express-mongo-sanitize/test.js' {
  declare module.exports: $Exports<'express-mongo-sanitize/test'>;
}
