// flow-typed signature: 2836eb19d731e5818649e1d2e9bb3492
// flow-typed version: <<STUB>>/gridfs-stream_v1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gridfs-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gridfs-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gridfs-stream/lib/index' {
  declare module.exports: any;
}

declare module 'gridfs-stream/lib/readstream' {
  declare module.exports: any;
}

declare module 'gridfs-stream/lib/writestream' {
  declare module.exports: any;
}

declare module 'gridfs-stream/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gridfs-stream/index' {
  declare module.exports: $Exports<'gridfs-stream'>;
}
declare module 'gridfs-stream/index.js' {
  declare module.exports: $Exports<'gridfs-stream'>;
}
declare module 'gridfs-stream/lib/index.js' {
  declare module.exports: $Exports<'gridfs-stream/lib/index'>;
}
declare module 'gridfs-stream/lib/readstream.js' {
  declare module.exports: $Exports<'gridfs-stream/lib/readstream'>;
}
declare module 'gridfs-stream/lib/writestream.js' {
  declare module.exports: $Exports<'gridfs-stream/lib/writestream'>;
}
declare module 'gridfs-stream/test/index.js' {
  declare module.exports: $Exports<'gridfs-stream/test/index'>;
}
