// flow-typed signature: c2d96c876fd470533093f2acc7a09ea2
// flow-typed version: <<STUB>>/jwks-rsa_v1.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwks-rsa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwks-rsa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwks-rsa/examples/express-demo/server' {
  declare module.exports: any;
}

declare module 'jwks-rsa/examples/hapi-demo/server' {
  declare module.exports: any;
}

declare module 'jwks-rsa/examples/koa-demo/server' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/errors/ArgumentError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/errors/index' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/errors/JwksError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/errors/JwksRateLimitError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/errors/SigningKeyNotFoundError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/index' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/integrations/express' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/integrations/hapi' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/integrations/koa' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/JwksClient' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/utils' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/wrappers/cache' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/wrappers/index' {
  declare module.exports: any;
}

declare module 'jwks-rsa/lib/wrappers/rateLimit' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/cache.tests' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/errors.es5.tests' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/express.es5.tests' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/jwksClient.tests' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/keys' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/koa.tests' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/mocks/jwks' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/mocks/keys' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/mocks/tokens' {
  declare module.exports: any;
}

declare module 'jwks-rsa/tests/rateLimit.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwks-rsa/examples/express-demo/server.js' {
  declare module.exports: $Exports<'jwks-rsa/examples/express-demo/server'>;
}
declare module 'jwks-rsa/examples/hapi-demo/server.js' {
  declare module.exports: $Exports<'jwks-rsa/examples/hapi-demo/server'>;
}
declare module 'jwks-rsa/examples/koa-demo/server.js' {
  declare module.exports: $Exports<'jwks-rsa/examples/koa-demo/server'>;
}
declare module 'jwks-rsa/lib/errors/ArgumentError.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/errors/ArgumentError'>;
}
declare module 'jwks-rsa/lib/errors/index.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/errors/index'>;
}
declare module 'jwks-rsa/lib/errors/JwksError.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/errors/JwksError'>;
}
declare module 'jwks-rsa/lib/errors/JwksRateLimitError.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/errors/JwksRateLimitError'>;
}
declare module 'jwks-rsa/lib/errors/SigningKeyNotFoundError.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/errors/SigningKeyNotFoundError'>;
}
declare module 'jwks-rsa/lib/index.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/index'>;
}
declare module 'jwks-rsa/lib/integrations/express.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/integrations/express'>;
}
declare module 'jwks-rsa/lib/integrations/hapi.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/integrations/hapi'>;
}
declare module 'jwks-rsa/lib/integrations/koa.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/integrations/koa'>;
}
declare module 'jwks-rsa/lib/JwksClient.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/JwksClient'>;
}
declare module 'jwks-rsa/lib/utils.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/utils'>;
}
declare module 'jwks-rsa/lib/wrappers/cache.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/wrappers/cache'>;
}
declare module 'jwks-rsa/lib/wrappers/index.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/wrappers/index'>;
}
declare module 'jwks-rsa/lib/wrappers/rateLimit.js' {
  declare module.exports: $Exports<'jwks-rsa/lib/wrappers/rateLimit'>;
}
declare module 'jwks-rsa/tests/cache.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/cache.tests'>;
}
declare module 'jwks-rsa/tests/errors.es5.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/errors.es5.tests'>;
}
declare module 'jwks-rsa/tests/express.es5.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/express.es5.tests'>;
}
declare module 'jwks-rsa/tests/jwksClient.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/jwksClient.tests'>;
}
declare module 'jwks-rsa/tests/keys.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/keys'>;
}
declare module 'jwks-rsa/tests/koa.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/koa.tests'>;
}
declare module 'jwks-rsa/tests/mocks/jwks.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/mocks/jwks'>;
}
declare module 'jwks-rsa/tests/mocks/keys.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/mocks/keys'>;
}
declare module 'jwks-rsa/tests/mocks/tokens.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/mocks/tokens'>;
}
declare module 'jwks-rsa/tests/rateLimit.tests.js' {
  declare module.exports: $Exports<'jwks-rsa/tests/rateLimit.tests'>;
}
