// flow-typed signature: 6b7f5a06377c9e77104242ea73d119dc
// flow-typed version: <<STUB>>/less-loader_v2.2.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-loader/stringify.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-loader/index' {
  declare module.exports: $Exports<'less-loader'>;
}
declare module 'less-loader/index.js' {
  declare module.exports: $Exports<'less-loader'>;
}
declare module 'less-loader/stringify.loader.js' {
  declare module.exports: $Exports<'less-loader/stringify.loader'>;
}
