// flow-typed signature: a9130cecbd06ccb43477fd827e20678d
// flow-typed version: <<STUB>>/mongoose-gridfs_v0.1.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-gridfs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-gridfs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-gridfs/lib/schema' {
  declare module.exports: any;
}

declare module 'mongoose-gridfs/lib/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-gridfs/index' {
  declare module.exports: $Exports<'mongoose-gridfs'>;
}
declare module 'mongoose-gridfs/index.js' {
  declare module.exports: $Exports<'mongoose-gridfs'>;
}
declare module 'mongoose-gridfs/lib/schema.js' {
  declare module.exports: $Exports<'mongoose-gridfs/lib/schema'>;
}
declare module 'mongoose-gridfs/lib/storage.js' {
  declare module.exports: $Exports<'mongoose-gridfs/lib/storage'>;
}
