// flow-typed signature: df84985109e7dec681d8bd18e918b35a
// flow-typed version: <<STUB>>/mongoose-sequence_v4.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-sequence/Gruntfile' {
  declare module.exports: any;
}

declare module 'mongoose-sequence/lib/sequence_archive' {
  declare module.exports: any;
}

declare module 'mongoose-sequence/lib/sequence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-sequence/Gruntfile.js' {
  declare module.exports: $Exports<'mongoose-sequence/Gruntfile'>;
}
declare module 'mongoose-sequence/index' {
  declare module.exports: $Exports<'mongoose-sequence'>;
}
declare module 'mongoose-sequence/index.js' {
  declare module.exports: $Exports<'mongoose-sequence'>;
}
declare module 'mongoose-sequence/lib/sequence_archive.js' {
  declare module.exports: $Exports<'mongoose-sequence/lib/sequence_archive'>;
}
declare module 'mongoose-sequence/lib/sequence.js' {
  declare module.exports: $Exports<'mongoose-sequence/lib/sequence'>;
}
