// flow-typed signature: 1c25ce42d4b5009a853daed812ac0cb9
// flow-typed version: <<STUB>>/pdffiller_v0.0.10/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdffiller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdffiller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdffiller/test/expected_data' {
  declare module.exports: any;
}

declare module 'pdffiller/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdffiller/index' {
  declare module.exports: $Exports<'pdffiller'>;
}
declare module 'pdffiller/index.js' {
  declare module.exports: $Exports<'pdffiller'>;
}
declare module 'pdffiller/test/expected_data.js' {
  declare module.exports: $Exports<'pdffiller/test/expected_data'>;
}
declare module 'pdffiller/test/test.js' {
  declare module.exports: $Exports<'pdffiller/test/test'>;
}
