// flow-typed signature: a871991ddca519a86728c6df18ae136b
// flow-typed version: <<STUB>>/react-countup_v2.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-countup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-countup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-countup/build/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'react-countup/build/index' {
  declare module.exports: any;
}

declare module 'react-countup/src/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'react-countup/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-countup/build/__tests__/index.test.js' {
  declare module.exports: $Exports<'react-countup/build/__tests__/index.test'>;
}
declare module 'react-countup/build/index.js' {
  declare module.exports: $Exports<'react-countup/build/index'>;
}
declare module 'react-countup/src/__tests__/index.test.js' {
  declare module.exports: $Exports<'react-countup/src/__tests__/index.test'>;
}
declare module 'react-countup/src/index.js' {
  declare module.exports: $Exports<'react-countup/src/index'>;
}
