// flow-typed signature: da8f4d7a045a461f5cfe0e06519b26e9
// flow-typed version: <<STUB>>/react-datatrans-lightbox_v1.0.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datatrans-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datatrans-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datatrans-lightbox/dist/Errors' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/dist/index' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/dist/Lightbox' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/dist/Provider' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/src/Errors' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/src/index' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-datatrans-lightbox/src/Provider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datatrans-lightbox/dist/Errors.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/dist/Errors'>;
}
declare module 'react-datatrans-lightbox/dist/index.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/dist/index'>;
}
declare module 'react-datatrans-lightbox/dist/Lightbox.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/dist/Lightbox'>;
}
declare module 'react-datatrans-lightbox/dist/Provider.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/dist/Provider'>;
}
declare module 'react-datatrans-lightbox/src/Errors.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/src/Errors'>;
}
declare module 'react-datatrans-lightbox/src/index.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/src/index'>;
}
declare module 'react-datatrans-lightbox/src/Lightbox.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/src/Lightbox'>;
}
declare module 'react-datatrans-lightbox/src/Provider.js' {
  declare module.exports: $Exports<'react-datatrans-lightbox/src/Provider'>;
}
