// flow-typed signature: 495ade0393c626ebd92272ecfcddc911
// flow-typed version: <<STUB>>/react-svg-inline-loader_v0.2.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-inline-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-inline-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-inline-loader/src/loader' {
  declare module.exports: any;
}

declare module 'react-svg-inline-loader/src/svgTemplate' {
  declare module.exports: any;
}

declare module 'react-svg-inline-loader/test/fixtures/test.component' {
  declare module.exports: any;
}

declare module 'react-svg-inline-loader/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-inline-loader/src/loader.js' {
  declare module.exports: $Exports<'react-svg-inline-loader/src/loader'>;
}
declare module 'react-svg-inline-loader/src/svgTemplate.js' {
  declare module.exports: $Exports<'react-svg-inline-loader/src/svgTemplate'>;
}
declare module 'react-svg-inline-loader/test/fixtures/test.component.js' {
  declare module.exports: $Exports<'react-svg-inline-loader/test/fixtures/test.component'>;
}
declare module 'react-svg-inline-loader/test/index.js' {
  declare module.exports: $Exports<'react-svg-inline-loader/test/index'>;
}
