// flow-typed signature: 47713b5bcaa479edf5a9dac5c7bcb702
// flow-typed version: <<STUB>>/react-drafts_v1.0.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-drafts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-drafts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-drafts/dist/react-drafts' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/divider' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/document' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/link' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/photo' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/rich' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/custom/table' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/decorators/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/decorators/link' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/ReactDrafts/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/shared/modal' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/shared/simple-dropdown' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/control' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/controls' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/document' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/link' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/photo' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/rich' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/table/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/components/Toolbar/inputs/table/table-row' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/constants/file' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/constants/keyboard' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/constants/toolbar' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/renderer/index' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/content' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/editor' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/export-to-html' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/import-from-html' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/inline' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/selection' {
  declare module.exports: any;
}

declare module 'react-drafts/lib/utils/toolbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-drafts/dist/react-drafts.js' {
  declare module.exports: $Exports<'react-drafts/dist/react-drafts'>;
}
declare module 'react-drafts/lib/components/custom/divider.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/divider'>;
}
declare module 'react-drafts/lib/components/custom/document.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/document'>;
}
declare module 'react-drafts/lib/components/custom/link.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/link'>;
}
declare module 'react-drafts/lib/components/custom/photo.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/photo'>;
}
declare module 'react-drafts/lib/components/custom/rich.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/rich'>;
}
declare module 'react-drafts/lib/components/custom/table.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/custom/table'>;
}
declare module 'react-drafts/lib/components/decorators/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/decorators/index'>;
}
declare module 'react-drafts/lib/components/decorators/link.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/decorators/link'>;
}
declare module 'react-drafts/lib/components/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/index'>;
}
declare module 'react-drafts/lib/components/ReactDrafts/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/ReactDrafts/index'>;
}
declare module 'react-drafts/lib/components/shared/modal.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/shared/modal'>;
}
declare module 'react-drafts/lib/components/shared/simple-dropdown.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/shared/simple-dropdown'>;
}
declare module 'react-drafts/lib/components/Toolbar/control.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/control'>;
}
declare module 'react-drafts/lib/components/Toolbar/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/index'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/controls.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/controls'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/document.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/document'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/link.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/link'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/photo.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/photo'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/rich.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/rich'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/table/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/table/index'>;
}
declare module 'react-drafts/lib/components/Toolbar/inputs/table/table-row.js' {
  declare module.exports: $Exports<'react-drafts/lib/components/Toolbar/inputs/table/table-row'>;
}
declare module 'react-drafts/lib/constants/file.js' {
  declare module.exports: $Exports<'react-drafts/lib/constants/file'>;
}
declare module 'react-drafts/lib/constants/keyboard.js' {
  declare module.exports: $Exports<'react-drafts/lib/constants/keyboard'>;
}
declare module 'react-drafts/lib/constants/toolbar.js' {
  declare module.exports: $Exports<'react-drafts/lib/constants/toolbar'>;
}
declare module 'react-drafts/lib/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/index'>;
}
declare module 'react-drafts/lib/renderer/index.js' {
  declare module.exports: $Exports<'react-drafts/lib/renderer/index'>;
}
declare module 'react-drafts/lib/utils/content.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/content'>;
}
declare module 'react-drafts/lib/utils/editor.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/editor'>;
}
declare module 'react-drafts/lib/utils/export-to-html.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/export-to-html'>;
}
declare module 'react-drafts/lib/utils/import-from-html.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/import-from-html'>;
}
declare module 'react-drafts/lib/utils/inline.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/inline'>;
}
declare module 'react-drafts/lib/utils/selection.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/selection'>;
}
declare module 'react-drafts/lib/utils/toolbar.js' {
  declare module.exports: $Exports<'react-drafts/lib/utils/toolbar'>;
}
