// flow-typed signature: 4cd1df266392a0264d643504a3956f3e
// flow-typed version: <<STUB>>/react-dragula_v1.1.17/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dragula'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dragula' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dragula/dist/react-dragula' {
  declare module.exports: any;
}

declare module 'react-dragula/dist/react-dragula.min' {
  declare module.exports: any;
}

declare module 'react-dragula/example/example' {
  declare module.exports: any;
}

declare module 'react-dragula/example/example' {
  declare module.exports: any;
}

declare module 'react-dragula/react-dragula' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dragula/dist/react-dragula.js' {
  declare module.exports: $Exports<'react-dragula/dist/react-dragula'>;
}
declare module 'react-dragula/dist/react-dragula.min.js' {
  declare module.exports: $Exports<'react-dragula/dist/react-dragula.min'>;
}
declare module 'react-dragula/example/example.js' {
  declare module.exports: $Exports<'react-dragula/example/example'>;
}
declare module 'react-dragula/example/example.jsx' {
  declare module.exports: $Exports<'react-dragula/example/example'>;
}
declare module 'react-dragula/react-dragula.js' {
  declare module.exports: $Exports<'react-dragula/react-dragula'>;
}
