// flow-typed signature: 9c5c4a7e26fb13104e1d1f31402ee723
// flow-typed version: <<STUB>>/streamifier_v0.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'streamifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'streamifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'streamifier/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'streamifier/lib/index.js' {
  declare module.exports: $Exports<'streamifier/lib/index'>;
}
