export default {
  SELECT_UPLOAD_FILES: 'SELECT_UPLOAD_FILES',
  PRODUCTS_LOADED: 'PRODUCTS_LOADED',
  PRODUCT_CATEGORIES_LOADED: 'PRODUCT_CATEGORIES_LOADED',
  PRODUCT_CATEGORY_SELECTED: 'PRODUCT_CATEGORY_SELECTED',
};
