export default {
  SELECT_UPLOAD_FILES: 'SELECT_UPLOAD_FILES',
  PRODUCTS_LOADED: 'PRODUCTS_LOADED',
  PRODUCT_CATEGORIES_LOADED: 'PRODUCT_CATEGORIES_LOADED',
  PRODUCT_CATEGORY_SELECTED: 'PRODUCT_CATEGORY_SELECTED',
  PRODUCER_SELECTED: 'PRODUCER_SELECTED',
  PRODUCERS_LOADED: 'PRODUCERS_LOADED',
  SUPPLIER_SELECTED: 'SUPPLIER_SELECTED',
  SUPPLIERS_LOADED: 'SUPPLIERS_LOADED',
  TRANSLATIONS_LOADED: 'TRANSLATIONS_LOADED',
};
